development:
  sessions:
    default:
      database: oauth_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: oauth_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017

production:
  sessions:
    default:
      database: oauth_production
      hosts:
        - <%= ENV['MONGOHQ_URL'] || ENV['DATABASE_URL'] %>:27017